config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :topics

  resources :bookmarks
  
  get 'welcome/index'
  get 'welcome/about'

root to: 'welcome#index'
end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
  has_many :bookmarks
end

app/models/user.rb
class User < ActiveRecord::Base
has_many :topics
has_many :bookmarks, dependent: :destroy
 
 devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  
   protected
 
   def configure_permitted_parameters
     devise_parameter_sanitizer.for(:sign_up) << :name
   end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  
  def index
    @bookmarks = Bookmark.all
    @mybookmarks = Bookmark.where(user_id: current_user.id) 
    authorize @bookmarks
  end

  def new
    @bookmark = Bookmark.new
    authorize @bookmark
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)

    authorize @bookmark
      if @bookmark.save
       redirect_to @bookmark, notice: "Bookmark was saved successfully."
      else
       flash[:error] = "Error creating bookmark. Please try again."
       render :new
      end 
  end
end

app/controllers/incoming_controller.rb
class IncomingController < ApplicationController

  skip_before_action :verify_authenticity_token, only: [:create]

  def create
    @user = User.where(email: params['sender']).first
    @topic = Topic.where(name: params[:subject]).first_or_create
    unless @user.name == "User"
    @topic.bookmarks.create(link: params['stripped-text'], user_id: @user.id)
    end
  head 200
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  def index
    @topics = Topic.all
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)
    
    if @topic.save
      redirect_to @topic, notice: "Topic was saved successfully."
    else
      flash[:error] = "Error creating topic. Try again."
      render :new
    end
  end

  def show
    @topic = Topic.find(params[:id])
    @bookmarks = @topic.bookmarks
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:id])
    
    if @topic.update_attributes(topic_params)
      redirect_to @topic
    else
      flash[:error] = "Error saving topic. Try again."
      render :edit
    end
  end

  def destroy 
    @topic = Topic.find(params[:id])
    
    if @topic.destroy
      flash[:notice] = "Successfully deleted."
      redirect_to topics_path
    else
      flash[:error] = "There was no error deleting the topic."
      render :show
    end
  end

  private

  def topic_params
    params.require(:topic).permit(:email, :name, :description, :public)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def index
    @users = User.find(params[:id])
  end

  def update
    if current_user.update_attributes(user_params)
      flash[:notice] = "User information updated"
      redirect_to edit_user_registration_path(current_user)
    else
      flash[:error] = "Invalid user information"
      redirect_to edit_user_registration_path
    end
  end

  def show
    @user = User.find(params[:id])
    @bookmarks = @user.bookmarks.visible_to(current_user)
  end




  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
 <html>
 <head>
   <title>BookMarks</title>
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <%= stylesheet_link_tag    "application", media: "all" %>
   <%= javascript_include_tag "application" %>
   <%= csrf_meta_tags %>
 </head>
 <body>
   <div class="container">
     <ul class="nav nav-tabs">
       <li><%= link_to "BookMarks", welcome_index_path %></li>
       <li><%= link_to "About", welcome_about_path %></li>
        <div class="pull-right user-info">
           <% if current_user %>
             Hello <%= current_user.email %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
           <% else %>
             <%= link_to "Sign In", new_user_session_path %> or
             <%= link_to "Sign Up", new_user_registration_path %>
           <% end %>
         </div>
     </ul>
      <% if flash[:notice] %>
         <div class="alert alert-success">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:notice] %>
         </div>
       <% elsif flash[:error] %>
         <div class="alert alert-danger">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:error] %>
         </div>
       <% elsif flash[:alert] %>
         <div class="alert alert-warning">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:alert] %>
         </div>
       <% end %>

      <%= yield %>
      </div>

  </body>
</html>


        

app/views/topics/edit.html.erb
<h1>Edit Topic</hi>

<div class="col-md-8">
   <%= form_for @topic do |f| %>
     <div class="form-group">
       <h3><%= f.label :name %></h3>
       <%= f.text_field :name, class: 'form-control', placeholder: "Enter topic name" %>
     </div>
      <%= f.submit "Save", class: 'btn btn-success' %>
    <% end %>
</div>
  

app/views/topics/index.html.erb
<h1>Topics</h1>

<div class="row">
  <div class="col-md-8">
    <% @topics.each do |topic| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to topic.name, topic %>
          </h4>
          <small>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-4">
    <%= link_to "New Topic", new_topic_path, class: 'btn btn-success' %>
  </div>
</div>

app/views/topics/new.html.erb
<h1>New Topic</hi>

<div class="col-md-8">
  <%= form_for @topic do |f| %>
    <div class="form-group">
      <%= f.label :name %>
       <%= f.text_field :name, class: 'form-control', placeholder: "Enter topic name" %>
    </div>
      <%= f.submit "Save", class: 'btn btn-success' %>
  <% end %>
</div>

app/views/topics/show.html.erb
<h1><%= @topic.name %></h1>

  <%= link_to "Edit Topic", edit_topic_path, class: 'btn btn-success' %>
 
  <%= link_to "Delete Topic", @topic, method: :delete, class: "btn btn-danger", data: { confirm: 'Are you sure you want to delete this topic' } %>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<br>
<div class="jumbotron">
  <h1>BookMarks</h1>
  <p>BookMarks is a social bookmarking app that allows users to email, manage and share bookmarked URLs.</p>
  <p>
      <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary' %> or
      <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %> today!
  </p>
</div>

<div class="row">
  <div class="col-md-4">
    <h3>BookMarks gets it's savvy name from a decorated paper strip that one uses to save their place in a book. </h3>
    
  </div>
  <div class="col-md-4">
    <h3>BookMarks is easy and fun to use.</h3>
    
  </div>
  <div class="col-md-4">
    <h3>BookMarks is an invaluable resource, unless of course, you'd like to pay us a specific fee to use it.</h3>
    
  </div>
</div>